# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/ubuntu-16.04-64-puppet"
  config.vm.box_version = "1.0.0"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--cpus", "2", "--memory", "1536"]
  end

  config.vm.define :master do |master|
    master.vm.network "private_network", ip: "192.168.7.10"
    master.vm.hostname = "master.local"
    
    master.vm.provision :puppet do |puppet|
      puppet.manifest_file = "master-single.pp"
      puppet.module_path = "../modules"
      puppet.manifests_path = "../manifests"
    end
  end
end
